const express = require('express');
require('dotenv').config();
const app = express();
const cors = require('cors');
const PORT = process.env.PORT || 8000;

app.use(express.json());
app.use(cors({
    origin: "http://localhost:5173",
    method: ['GET', 'POST'],
    credentials: true
}))

const authRouter = require('./router/authRouter');
const catchAsync = require('./utils/catchAsync');
const AppError = require('./utils/appError');
const globalErrorHandler = require('./controller/globalErrorHandler/globalErrorHandler');
const projectRouter = require('./router/projectRouter');
const { Server } = require("socket.io");
const { createServer } = require('node:http');
const server = createServer(app);
const io = new Server(server, {
    cors: {
        origin: "http://localhost:5173",
        method: ['GET', 'POST'],
        credentials: true
    }
});





io.on('connection', (socket) => {
    console.log('a user connected');
    console.log(`user id ${socket.id}`);

    socket.emit('welcome', `Welcome to the server ${socket.id}`);
    // socket.broadcast.emit('welcome', `welcome user`);


    socket.on('disconnect', ()=>{
        console.log(`User disconnected ${socket.id}`)
    })
})






//all routes will be here
app.use('/api/v1/auth', authRouter);
app.use('/api/v1/project', projectRouter);

app.use('*',
    catchAsync(async (req, res, next) => {
        // provide custom error message generated by user
        throw new AppError(`Can't find ${req.originalUrl} on this server`, 404)

        // provide error message through global error handler by using catchAsync middleware way without using try catch block
        // throw new Error(`Can't find ${req.originalUrl} on this server`);

        // provide default error message  through global error handler for async function
        // return next(new Error(`Can't find ${req.originalUrl} on this server`))

        // provide error message through global error handler for normal function
        // throw new Error(`Can't find ${req.originalUrl} on this server`);

        // default way to provide error message 
        // res.status(404).json({
        //     status: 'fail',
        //     message: `Can't find ${req.originalUrl} on this server`
        // })
    }))

//global error handler
app.use(globalErrorHandler);

server.listen(PORT, () => {
    console.log(`Server is running on port ${PORT}`);
});